stages:
  - build
  - test
  - push_to_dockerhub
  - deploy

build_job:
  stage: build
  script:
    - docker build -t node-app:latest .
  tags:
    - dev

test_job:
  stage: test
  script:
    - echo "testing"
  tags:
    - dev

push_job:
  stage: push_to_dockerhub
  script:
    - docker login $docker_user -p $docker_pass
    - docker image tag node-app:latest $docker_user/node-app:latest
    - docker push $docker_user/node-app:latest
  tags:
    - dev

deploy_job:
  stage: deploy
  scripts:
    - docke-compose up -d
  tags:
    - dev
